import { ProductProps } from "@/interface/product";

export const products: ProductProps[] = [
  {
    productId: "1",
    prouductPhoto: "/artwork/artwork1.jpg", // Example photo path
    productArtist: "Marius Williams",
    productTitle: "Hope Beyond Bars",
    productCategory: "Non Religious",
    productPrice: 850,
    auctionPrice: 420,
    remainingTime: new Date("2026-01-18T12:00:00Z"),
    isSoldOut: false,
  },
  {
    productId: "2",
    prouductPhoto: "/artwork/artwork2.jpg",
    productArtist: "James Carter",
    productTitle: "Divine Light",
    productCategory: "Religious",
    productPrice: 1200,
    auctionPrice: 875,
    remainingTime: new Date("2026-01-18T12:00:00Z"),
    isSoldOut: false,
  },
  {
    productId: "3",
    prouductPhoto: "/artwork/artwork3.jpg",
    productArtist: "DeShawn Jackson",
    productTitle: "Urban Dreams",
    productCategory: "Non Religious",
    productPrice: 650,
    auctionPrice: 575,
    remainingTime: new Date("2026-01-18T12:00:00Z"),
    isSoldOut: true,
  },
  {
    productId: "4",
    prouductPhoto: "/artwork/artwork4.jpg",
    productArtist: "Carlos Rodriguez",
    productTitle: "Redemption Path",
    productCategory: "Religious",
    productPrice: 650,
    auctionPrice: 850,
    remainingTime: new Date("2026-01-18T12:00:00Z"),
    isSoldOut: false,
  },
  {
    productId: "5",
    prouductPhoto: "/artwork/artwork5.jpg",
    productArtist: "Andre Thompson",
    productTitle: "Freedom in Color",
    productCategory: "Non Religious",
    productPrice: 720,
    auctionPrice: 500,
    remainingTime: new Date("2026-01-18T12:00:00Z"),
    isSoldOut: false,
  },
  {
    productId: "6",
    prouductPhoto: "/artwork/artwork6.jpg",
    productArtist: "Michael Davis",
    productTitle: "Sacred Sanctuary",
    productCategory: "Religious",
    productPrice: 1100,
    auctionPrice: 820,
    remainingTime: new Date("2026-01-18T12:00:00Z"),
    isSoldOut: false,
  },
  {
    productId: "7",
    prouductPhoto: "/artwork/artwork7.jpg",
    productArtist: "Robert Lee",
    productTitle: "Metamorphosis",
    productCategory: "Non Religious",
    productPrice: 880,
    auctionPrice: 640,
    remainingTime: new Date("2026-01-18T12:00:00Z"),
    isSoldOut: false,
  },
  {
    productId: "8",
    prouductPhoto: "/artwork/artwork4.jpg",
    productArtist: "Steven Baker",
    productTitle: "Grace and Mercy",
    productCategory: "Religious",
    productPrice: 1350,
    auctionPrice: 950,
    remainingTime: new Date("2026-01-18T12:00:00Z"),
    isSoldOut: false,
  },
  {
    productId: "9",
    prouductPhoto: "/artwork/artwork2.jpg",
    productArtist: "Patrick Moore",
    productTitle: "Behind the Wall",
    productCategory: "Non Religious",
    productPrice: 775,
    auctionPrice: 950,
    remainingTime: new Date("2026-01-18T12:00:00Z"),
    isSoldOut: true,
  },
];
