name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🚀 SSH & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            echo "📂 Going to project directory..."
            cd /home/ubuntu/my-project/artbehindbars

            echo "🔄 Pulling latest code..."
            git pull origin main

            echo "🐳 Building Docker image..."
            docker compose build frontend

            echo "🚀 Starting containers..."
            docker compose up -d frontend

            echo "🧹 Cleaning unused images..."
            docker image prune -f

            echo "✅ Deployment successful"